server:
  port: 30301

# spring 配置
spring:
  application:
    name: alinesno-infra-data-report-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_data_report_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: admin
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  devtools:
    restart:
      enabled: true
  kafka:
    bootstrap-servers: 192.168.204.130:9092
      
actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.data.report.entity;
  database:
    type: mysql
  index:
    prefix: alinesno_data_report_idx_
  unique:
    prefix: alinesno_data_report_uni_

minio:
  endpoint: http://127.0.0.1:9000
  accesskey: minioadmin
  secretkey: minioadmin
  bucketname: alinesnoinfradatareport
  port: 19000
  local-storage-path: D:/alinesno-data-report/

# sa-token配置
sa-token:
  token-name: satoken
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key:
